### ISSUE TITLE
Parameters passed do not match required

### ISSUE THREAD

**Issue by yzysmile** [PRBonn/point-cloud-prediction#11]
Thank you for this great work.
I run pcf/train.py but i found pycharm throw out mistakes about parameters passed do not match required.
To specifically, it seems that the class Trainer constructor in trainer.py does not match the parameter name passed in by the trainer object in train.py.
There are error information below.  "TypeError: __init__() got an unexpected keyword argument 'gpus' "
                                                        "TypeError: __init__() got an unexpected keyword argument 'resume_from_checkpoint' "
I think that "num_nodes" should be changed to "gpus". If i am correct, Which parameter does resume_from_checkpoint correspond to?

Looking forward to your response, thanks!

**Comment by benemer** [comment]
Which pytorch_lightning version do you use? Currently, point-cloud-prediction requires pytorch-lightning<2.0.0 and >=1.5.0.

However, I just created a branch [benedikt/migrate_pytorch_lightning](https://github.com/PRBonn/point-cloud-prediction/tree/benedikt/migrate_pytorch_lightning) that migrates to pytorch-lightning>2.0.0, can you please check if this works for you?

**Comment by yzysmile** [comment]
> Which pytorch_lightning version do you use? Currently, point-cloud-prediction requires pytorch-lightning<2.0.0 and >=1.5.0.
> 
> However, I just created a branch [benedikt/migrate_pytorch_lightning](https://github.com/PRBonn/point-cloud-prediction/tree/benedikt/migrate_pytorch_lightning) that migrates to pytorch-lightning>2.0.0, can you please check if this works for you?

Thank your response so quickly. I have check the version of pytorch-lightning, It does > 2.0.0, and I restall a new version that required, it works.  Thanks again!

**Comment by benemer** [comment]
Great, happy to hear that :)
