### ISSUE TITLE
run test.py  error

### ISSUE THREAD

**Issue by lxdunan** [PRBonn/point-cloud-prediction#13]
Hi author,
When I run the test.py , 
TypeError: on_test_epoch_end() missing 1 required positional argument: 'outputs'
How can I deal it?

**Comment by lxdunan** [comment]
![webwxgetmsgimg](https://github.com/PRBonn/point-cloud-prediction/assets/132971083/0713bd72-8a49-4159-9d2f-86b5fcfbdb33)

**Comment by benemer** [comment]
The `outputs` argument got deprecates, see https://github.com/Lightning-AI/pytorch-lightning/discussions/17182#discussioncomment-5536583. Since we anyway don't use it, I removed in on https://github.com/PRBonn/point-cloud-prediction/pull/14.

Can you please check if it works on this branch?

**Comment by lxdunan** [comment]
It is OK now, Thank you.  But the new issue is that when I run  visualize.py ,no points can be seen in the open3D. We have got point clouds and range images by test.py. Do you know why?

**Comment by benemer** [comment]
Do you provide the path to the predictions as described [here](ttps://github.com/PRBonn/point-cloud-prediction/tree/main?tab=readme-ov-file#visualization)? If the folder is not empty, but it should work. But that's hard to debug from here without the predictions.
