### ISSUE TITLE
MEANs and STDs in parameters.yml

### ISSUE THREAD

**Issue by qifang804** [PRBonn/point-cloud-prediction#3]
Hi Benedikt,

Thank you for providing this elegant and powerful repo and I really appreciate your brilliant work! 

I noticed that there are 5 means and 5 stds declared in parameters.yml.

Are they the means and stds of 5 channels(range, x, y, z, intensity) of the whole training set?

Thank you in advance!

**Comment by benemer** [comment]
Hi n0tva1id,

Thank you for your feedback. Yes, you are right, the 5 mean and std values were computed for the (range, x, y, z, intensity) channels of the training set. You can compute and display them by setting ```COMPUTE_MEAN_AND_STD: True``` in the ```parameters.yml```.

We now added some comments in the ```parameters.yml``` to make it more clear, please have a look at commit https://github.com/PRBonn/point-cloud-prediction/commit/88fcf005d0f2b5845f464111704f6dd3175b12b4.

Thank you!
