### ISSUE TITLE
Regarding N_FUTURE STEPS in config

### ISSUE THREAD

**Issue by prashkmr** [PRBonn/point-cloud-prediction#5]
Hi,

I had a doubt regarding the n_future steps in the config files. 
N_PAST_STEPS: 5 # Number of input range images
N_FUTURE_STEPS: 5 # Number of predicted future range images

I wanted to use this network as a simple generative model to reconstruct the input LIDAR back.

As far as I can read, would putting the above 2 config variables as 1 help in the making the network a simple generative model with the aim of only reconstructing the input LiDAR frame.

Eagerly awaiting the response of the authors.

**Comment by benemer** [comment]
Hi @prashkmr,

Yes, for this you would need to use 1 for both parameters. You also need to set the kernel size along the temporal dimension to 1 since the size of the features along this dimension will always be 1:

```yaml
  TEMPORAL_KERNEL_SIZE:
    - 1
    - 1
    - 1
    - 1
    - 1
```

Best regards!
